### ISSUE TITLE
Doesn't work :'(

### ISSUE THREAD

**Issue by lionel1704** [syedjafer/Dns-Python#1]
I tried running the script but it doesn't work for any of the domains listed in `domains.txt`

This is my output

```
==>> [+] Domain Data is Not Found for 5mi.in
==>> [+] Domain Data is Not Found for jascuahsckbsayd.in
==>> [+] Domain Data is Not Found for syedjafer.me
==>> [+] Domain Data is Not Found for facebook.com
==>> [+] Domain Data is Not Found for google.com
==>> [+] Domain Data is Not Found for guru.com
```

**Comment by syedjafer** [comment]
you must install dns-python 
`pip install dnspython`
then execute the script . 
`The DNS response does not contain an answer to the question: 5mi.in. IN TXT
[+] Domain Data are been collecting for 5mi.in
==>> [+] Domain Data is Not Found for jascuahsckbsayd.in
[+] Domain Data are been collecting for syedjafer.me
[+] Domain Data are been collecting for facebook.com
[+] Domain Data are been collecting for google.com
[+] Domain Data are been collecting for guru.com
The DNS response does not contain an answer to the question: domain.name. IN A
The DNS response does not contain an answer to the question: domain.name. IN NS
The DNS response does not contain an answer to the question: domain.name. IN SOA
The DNS response does not contain an answer to the question: domain.name. IN TXT
`

**Comment by syedjafer** [comment]
This is an old version . Try it you will get the results .
